name: AppflowLiveUpdates

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - 'hotfix/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-live-update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Build Live Update with Appflow
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.IONIC_TOKEN }}
          app-id: c46af4ba
          platform: Web
          environment: GitHub
