name: AppflowLiveUpdates

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - 'hotfix/**'
env:
  IONIC_TOKEN: ${{ secrets.IONIC_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-live-update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x

      - name: Install Ionic CLI
        run: npm i -g @ionic/cli@6.11.11

      - run: ionic deploy build --environment="GitHub" --Channel="Production"
